[package]
name = "roca"
version = "0.1.0"
authors = ["Christian González <cgonzalez@opennebula.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmlrpc = "0.13.1"
